version: "3.9"
services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      cvwo:

  gateway:
    hostname: gateway
    build: .
    image: cvwo-backend:latest
    command: ./gateway
    depends_on:
      - auth
    ports: 
      - "8080:8080"
    environment:
      - CVWO_AUTH_SERVICE_URL=auth:8080

  auth:
    hostname: auth
    depends_on:
      database:
        condition: service_healthy
    build: .
    image: cvwo-backend:latest
    command: ./auth
    environment:
      - CVWO_DATABASE_URL=postgres://postgres:password@database:5432
      - CVWO_JWT_SECRET=woah
    networks:
      cvwo:

  user:
    hostname: user
    depends_on:
      database:
        condition: service_healthy
    build: .
    image: cvwo-backend:latest
    command: ./user
    environment:
      - CVWO_DATABASE_URL=postgres://postgres:password@database:5432
    networks:
      cvwo:
  thread:
    hostname: user
    depends_on:
      database:
        condition: service_healthy
    build: .
    image: cvwo-backend:latest
    command: ./user
    environment:
      - CVWO_DATABASE_URL=postgres://postgres:password@database:5432
    networks:
      cvwo:


networks:
  cvwo:
